#define WHITE { HSV_WHITE }
#define RED { HSV_RED }
#define CORAL { HSV_CORAL }
#define ORANGE { HSV_ORANGE }
#define GOLDENROD { HSV_GOLDENROD }
#define GOLD { HSV_GOLD }
#define YELLOW { HSV_YELLOW }
#define CHARTREUSE { HSV_CHARTREUSE }
#define GREEN { HSV_GREEN }
#define SPRINGGREEN { HSV_SPRINGGREEN }
#define TURQUOISE { HSV_TURQUOISE }
#define TEAL { HSV_TEAL }
#define CYAN { HSV_CYAN }
#define AZURE { HSV_AZURE }
#define BLUE { HSV_BLUE }
#define PURPLE { HSV_PURPLE }
#define MAGENTA { HSV_MAGENTA }
#define PINK { HSV_PINK }
#define NONE {0,0,0}

PROGMEM uint8_t ledmap[][DRIVER_LED_TOTAL][3] = {
    [MacbookLayer] = {
        ORANGE, CYAN, CYAN, CYAN, ORANGE,
        SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, NONE,
        SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, ORANGE,
        SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, CYAN,
        SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, CYAN,
        SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN,
        SPRINGGREEN, SPRINGGREEN, ORANGE,
        SPRINGGREEN, GOLD, MAGENTA,
        WHITE,

        CYAN, SPRINGGREEN, CYAN, CYAN, GOLD,
        SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, GOLD,
        SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, GOLD,
        SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, GOLD,
        SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN,
        SPRINGGREEN, SPRINGGREEN, SPRINGGREEN, SPRINGGREEN,
        SPRINGGREEN, ORANGE, ORANGE,
        WHITE, CYAN, MAGENTA,
        WHITE },

    [WindowsLayer] = {
        CORAL, GREEN, GREEN, GREEN, CORAL,
        CYAN, CYAN, CYAN, CYAN, NONE,
        CYAN, CYAN, CYAN, CYAN, CORAL, 
        CYAN, CYAN, CYAN, CYAN, GREEN,
        CYAN, CYAN, CYAN, CYAN, GREEN,
        CYAN, CYAN, CYAN, CYAN,
        CYAN, CYAN, CORAL,
        CYAN, GOLD, BLUE,
        WHITE,

        GREEN, CYAN, GREEN, GREEN, GOLD,
        CYAN, CYAN, CYAN, CYAN, GOLD,
        CYAN, CYAN, CYAN, CYAN, GOLD,
        CYAN, CYAN, CYAN, CYAN, GOLD,
        CYAN, CYAN, CYAN, CYAN, CYAN,
        CYAN, CYAN, CYAN, CYAN,
        CYAN, CORAL, CORAL,
        WHITE, GOLD, BLUE,
        WHITE },

    [GameLayer] = {
        ORANGE, NONE, NONE, ORANGE, ORANGE,
        NONE, NONE, GOLD, NONE, NONE,
        NONE, GOLD, GOLD, NONE, NONE,
        NONE, NONE, GOLD, NONE, BLUE,
        NONE, NONE, NONE, NONE, ORANGE,
        NONE, NONE, NONE, NONE,
        NONE, NONE, RED,
        WHITE, NONE, NONE,
        BLUE,

        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE, GOLD,
        NONE, NONE, NONE, GOLD, GOLD,
        NONE, NONE, NONE, NONE, GOLD,
        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE,
        NONE, NONE, NONE,
        NONE, NONE, NONE,
        NONE },

    [SymbolLayer] = {
        PINK, MAGENTA, MAGENTA, MAGENTA, PINK,
        NONE, CYAN, NONE, NONE, NONE,
        NONE, CYAN, GOLD, NONE, NONE,
        NONE, CYAN, GOLD, NONE, MAGENTA,
        NONE, CYAN, GOLD, NONE, MAGENTA,
        NONE, CYAN, NONE, NONE,
        NONE, CYAN, NONE,
        NONE, NONE, NONE,
        NONE,

        ORANGE, CORAL, NONE, NONE, NONE,
        NONE, CORAL, CYAN, CYAN, NONE,
        NONE, GOLD, CYAN, CYAN, NONE,
        NONE, GOLD, CYAN, CYAN, NONE,
        NONE, ORANGE, GREEN, GREEN, CYAN,
        NONE, NONE, ORANGE, ORANGE,
        ORANGE, NONE, NONE,
        SPRINGGREEN, SPRINGGREEN, NONE,
        NONE },

    [MouseLayer] = {
        NONE, NONE, CYAN, CYAN, NONE,
        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE, CYAN,
        NONE, NONE, NONE, NONE, CYAN,
        NONE, NONE, NONE, NONE,
        NONE, NONE, NONE,
        NONE, NONE, NONE,
        NONE,

        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, AZURE, NONE, NONE,
        NONE, RED, GOLD, BLUE, NONE,
        NONE, GOLD, GOLD, BLUE, NONE,
        NONE, RED, GOLD, BLUE, NONE,
        NONE, NONE, RED, RED,
        NONE, NONE, NONE,
        MAGENTA, YELLOW, MAGENTA,
        NONE
    },

    [NumpadLayer] = {
        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE,
        NONE, NONE, NONE,
        NONE, NONE, NONE,
        NONE,

        NONE, NONE, NONE, NONE, NONE,
        RED, GREEN, WHITE, NONE, NONE,
        ORANGE, TURQUOISE, TURQUOISE, TURQUOISE, NONE,
        MAGENTA, TURQUOISE, TURQUOISE, TURQUOISE, GOLD,
        WHITE, TURQUOISE, TURQUOISE, TURQUOISE, TURQUOISE,
        NONE, NONE, NONE, NONE,
        NONE, NONE, NONE,
        TURQUOISE, TURQUOISE, NONE,
        NONE
    },

    [FuncLayer] = {
        NONE, NONE, NONE, NONE, WHITE,
        CHARTREUSE, RED, NONE, NONE, NONE,
        CHARTREUSE, NONE, GOLDENROD, YELLOW, NONE,
        CHARTREUSE, NONE, GOLD, GREEN, NONE,
        CHARTREUSE, NONE, GOLDENROD, YELLOW, NONE,
        CHARTREUSE, NONE, WHITE, WHITE,
        CHARTREUSE, NONE, MAGENTA,
        NONE, GOLD, ORANGE,
        NONE,

        CHARTREUSE, CHARTREUSE, NONE, NONE, WHITE,
        CHARTREUSE, NONE, NONE, NONE, NONE,
        CHARTREUSE, NONE, WHITE, WHITE, NONE,
        CHARTREUSE, NONE, CYAN, YELLOW, NONE,
        CHARTREUSE, NONE, CYAN, YELLOW, PURPLE,
        CHARTREUSE, NONE, WHITE, WHITE,
        CHARTREUSE, NONE, RED,
        NONE, MAGENTA, ORANGE,
        NONE
    },

    [ArrowsLayer] = {
        NONE, NONE, WHITE, WHITE, NONE,
        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, PINK, NONE,
        NONE, PINK, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE, WHITE,
        NONE, NONE, NONE, NONE,
        NONE, NONE, NONE,
        NONE, NONE, NONE,
        NONE,

        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, NONE, NONE, NONE,
        NONE, NONE, GOLD, NONE, NONE,
        NONE, PINK, GOLD, NONE, NONE,
        NONE, NONE, GOLD, NONE, NONE,
        NONE, NONE, GOLD, NONE,
        NONE, NONE, NONE,
        NONE, MAGENTA, MAGENTA,
        NONE
    },
};

