BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

WEBUSB_ENABLE = yes
ORYX_ENABLE = yes
TAP_DANCE_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes

SRC = matrix.c

#custom
RGB_MATRIX_CUSTOM_USER = yes
BLUETOOTH_ENABLE = no
RAW_ENABLE = no
